### ISSUE TITLE
Error when running "npm run dev"

### ISSUE THREAD

**Issue by nkuxgroup** [mariorodeghiero/git-commands#2]
I tried installing this on a macbook. After running clone and yarn I went into the `your-project-name` directory and ran `npm run dev` and was given this error.

> ERROR in ./app/containers/HomePage.js
> Module not found: Error: Can't resolve '../components/main/Main' in '/Users/alex/Documents/git_cheatsheet/your-project-name/app/containers'
>  @ ./app/containers/HomePage.js 13:12-46
>  @ ./app/routes.js
>  @ ./app/containers/Root.js
>  @ ./app/index.js
>  @ multi (webpack)-dev-server/client?http://localhost:1212 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js
> Not rewriting GET /dist/renderer.dev.js because the path includes a dot (.) character.

**Comment by mariorodeghiero** [comment]
Hi, which operating system and editor are you using? In my case, I used the Mac OS and Vs code.
It seems to present one in the "./path", for the VS code, you can use the ESLINT extension and try to identify if some module import is incorrect.
Even so, I will download to my Windows and test.

Try importing the react directly (import React, {Component} from 'react';) in "main.js"

You can also read about the boilerplate used in the project and compare the module imports. Because I had to change some.
 then return if it worked.

**Comment by mariorodeghiero** [comment]
@nkuxgroup I made this product on another Mac and it worked, try to perform ...

# Installation Failure

This aims to be a list of solutions for installation issues with this project:

1 - Fix node-gyp issues:
Follow the steps in https://github.com/nodejs/node-gyp#installation. You don't need to install node-gyp but make sure that you have the correct environment setup for your OS.

2 - Test installation against latest npm/node version

3 - Fix Caching Issues

```rm -rf node_modules ```
```npm cache clean --force```
```npm i```
```npm rb```
```npm run dev```

4 - If you're on Windows, try using cmder

5 - Try reinstalling the dependencies with npm. Make sure to clear all cache and before removing and installing node modules with npm

**Comment by nkuxgroup** [comment]
So I was able to get it working. I just tried reinstalling from scratch. This time I used node 8 instead of the latest node 10 version. I'm not sure if that is what was causing the problem though.

**Comment by mariorodeghiero** [comment]
Good news possibly may be the version of the node. So I'll close the issue.
Thanks for the feedback.
