### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:1212/dist/renderer.dev.js

### ISSUE THREAD

**Issue by pavanyogi** [mariorodeghiero/git-commands#4]
pavan@pavan-u14:~/.../git-commands$ npm run dev

> electron-react-boilerplate@0.13.3 dev /home/pavan/Downloads/softwares/git-commands/git-commands
> cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev

> electron-react-boilerplate@0.13.3 start-renderer-dev /home/pavan/Downloads/softwares/git-commands/git-commands
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js

Starting Main Process...

> electron-react-boilerplate@0.13.3 start-main-dev /home/pavan/Downloads/softwares/git-commands/git-commands
> cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js

✖ ｢wdm｣: 
ERROR in ./app/components/home-1/Home.js
Module not found: Error: Can't resolve '../header/Header' in '/home/pavan/Downloads/softwares/git-commands/git-commands/app/components/home-1'
 @ ./app/components/home-1/Home.js 21:14-41
 @ ./app/containers/HomePage.js
 @ ./app/routes.js
 @ ./app/containers/Root.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 (webpack)/hot/dev-server.js react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js
Not rewriting GET /dist/renderer.dev.js because the path includes a dot (.) character.

**Comment by mariorodeghiero** [comment]
Which operating system and editor are you using? In my case, I used the Mac OS and Vs code.
It seems to present one in the "./path", for the VS code, you can use the ESLINT extension and try to identify if some module import is incorrect.

You can also read about the boilerplate used in the project and compare the module imports. Because I had to change some.

https://github.com/chentsulin/electron-react-boilerplate

I hope it helps, then return if it worked.
